# StorageClass for AWS EBS (CSI driver for Kubernetes 1.27+)
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-ebs-pv
provisioner: ebs.csi.aws.com # For legacy k8s < 1.27: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  zones: us-east-1a